---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.34.0
          ports:
            - containerPort: 9090
          securityContext:
            readOnlyRootFilesystem: true  # Set the root filesystem to read-only
            runAsNonRoot: true             # Ensure the container runs as a non-root user
            runAsUser: 1000               # Set a non-zero user ID (non-root)
          resources:
            requests:
              memory: "256Mi"  # Set memory request for the container
              cpu: "250m"      # Set CPU request for the container
            limits:
              memory: "512Mi"  # Set memory limit for the container
              cpu: "500m"      # Set CPU limit for the container
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: istio-system
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus
  type: ClusterIP
