---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default  # Ensured namespace is set correctly
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app  # Ensure it matches the service selector
  template:
    metadata:
      labels:
        app: flask-app  # Ensure the pod label matches the service selector
        prometheus: main  # Add the prometheus label
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ vars.FLASK_PORT }}"  # Replace with the correct port
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: flask-app
        image: jjorozco20/flask-mysql-app:1.0.0  # Updated image version
        ports:
        - containerPort: "{{ vars.FLASK_PORT }}"  # Flask app runs on the specified port
        env:
        - name: MYSQL_HOST
          value: "${{ vars.MYSQL_HOST }}"  # GitHub Actions secret for MySQL host
        - name: MYSQL_PORT
          value: "${{ vars.MYSQL_PORT }}"  # GitHub Actions secret for MySQL port
        - name: MYSQL_USER
          value: "${{ vars.MYSQL_USER }}"  # GitHub Actions secret for MySQL user
        - name: MYSQL_PASSWORD
          value: "${{ secrets.MYSQL_PASSWORD }}"  # GitHub Actions secret for MySQL password
        - name: MYSQL_DB
          value: "${{ vars.MYSQL_DB }}"  # GitHub Actions secret for MySQL database     securityContext:
          runAsUser: 1000
          runAsNonRoot: true
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "200m"
            memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: default  # Ensured namespace is set correctly
spec:
  ports:
    - port: "{{ vars.FLASK_PORT }}"  # Flask app runs on the specified port inside the cluster     protocol: TCP
      targetPort: "{{ vars.FLASK_PORT }}"
  selector:
    app: flask-app  # Ensure the selector matches the label in Deployment
  type: ClusterIP  # Expose the service on a cluster-internal IP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  namespace: default  # Ensured namespace is set correctly
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ vars.PROMETHEUS_PORT }}"   # Replace with the correct port if different
    prometheus.io/path: "/metrics"

spec:
  ingressClassName: nginx
  rules:
  - host: flask.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-app  # Service name correctly referenced
            port:
              number: "{{ vars.FLASK_PORT }}"
