---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: default  # Added namespace
spec:
  capacity:
    storage: 5Gi  # Specify 5 GiB of storage
  accessModes:
    - ReadWriteOnce  # Access mode (single node read/write)
  hostPath:
    path: "/mnt/c/Users/Juan.Orozco/Desktop/kubernetes-kubeadm-kubelet-nginx-onpremise"  # Adjust for your Windows/Linux environment
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default  # Added namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Request the same size as the PV

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default  # Added namespace
type: Opaque
data:
  password: "rootpassword"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default  # Added namespace
  labels:
    app: mysql
    prometheus: main  # Add the prometheus label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3306"
        prometheus.io/path: "/metrics" # Use a metrics exporter for MySQL
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: db-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          value: "testdb"  # Database name
        volumeMounts:
        - mountPath: /var/lib/mysql  # MySQL data directory
          name: mysql-data
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "200m"
            memory: "1Gi"
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc  # Reference the PVC
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default  # Added namespace
  labels:
    app: mysql
spec:
  ports:
    - protocol: TCP
      port: 3306  # MySQL default port
      targetPort: 3306
      name: mysql-port
  selector:
    app: mysql
  type: ClusterIP
