name: CI Pipeline for Kubernetes Manifests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-k8s-manifests:
    runs-on: self-hosted
    environment: devops-training  # Environment defined for GitHub Actions

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Substitute environment variables in existing Kubernetes manifests
      - name: Render Kubernetes Manifests
        run: |
          # Replace environment variables in flask-app-deployment.yaml
          envsubst < manifests/flask-app-deployment.yaml > manifests/flask-app-deployment.yaml.tmp && mv manifests/flask-app-deployment.yaml.tmp manifests/flask-app-deployment.yaml

          # Replace environment variables in mysql-deployment.yaml
          envsubst < manifests/mysql-deployment.yaml > manifests/mysql-deployment.yaml.tmp && mv manifests/mysql-deployment.yaml.tmp manifests/mysql-deployment.yaml

      # Step 3: Run dry-run for Kubernetes manifests
      - name: Validate Kubernetes Manifests
        run: |
          kubectl apply --dry-run=client -f manifests/
